Repository ec-europa/ec_europa, pull requests merged in 2019-04, with the labels that each got.

#117 Issue #116: Fix easy_breadcrumb component.
  templates/easy_breadcrumb/easy_breadcrumb.component.inc
Labels: Ready to review

#118 Issue #116: Breadcrumb component update
  sass/style.scss
  templates/easy_breadcrumb/easy-breadcrumb.tpl.php
  templates/easy_breadcrumb/easy_breadcrumb.component.inc
Labels: Ready to review, bug

#129 Issue #128: Field component update.
  templates/field/field.component.inc
  templates/field/field.tpl.php
  templates/item_list/item-list--field.tpl.php
Labels: bug

#133 Issue #132: Fix menu link to properly display Login/logout link as ECL.
  templates/menu_link/menu_link.component.inc
Labels: bug

#134 Issue #132: Fix menu link to properly display Login/logout link as ECL.
  .gitignore
  templates/menu_link/menu_link.component.inc
Labels: Needs work, bug
