Repository ec-europa/ec_europa, pull requests merged in 2019-03, with the labels that each got.

#82 Issue #81: Use Docker based development environment.
  .drone.yml
  .editorconfig
  .gitignore
  composer.json
  docker-compose.yml
  grumphp.yml.dist
  includes/alter/form.inc
  phpunit.xml.dist
  runner.yml.dist
  template.php
  templates/atomium_overview/atomium-overview.tpl.php
  templates/block/block.component.inc
  templates/comment/comment.component.inc
  templates/comment_wrapper/comment_wrapper.component.inc
  templates/ds/ds-1col-wrapper.tpl.php
  templates/easy_breadcrumb/easy_breadcrumb.component.inc
  templates/expandable/expandable.component.inc
  templates/field/field.component.inc
  templates/file_widget/file_widget.component.inc
  templates/form_element/form-element.tpl.php
  templates/form_element_label/form_element_label.component.inc
  templates/html/html.component.inc
  templates/html_tag/html_tag.component.inc
  templates/item_list/item_list.component.inc
  templates/lang_select_site/lang_select_site.component.inc
  templates/language_selector_site_language_list/language_selector_site_language_list.component.inc
  templates/link_blocks/link_blocks.component.inc
  templates/maintenance_page/maintenance_page.component.inc
  templates/media/media-avportal-video.tpl.php
  templates/menu_link/menu_link.component.inc
  templates/menu_tree/menu_tree.component.inc
  templates/node/node.component.inc
  templates/page/page.component.inc
  templates/page_header/page-header.tpl.php
  templates/pager/pager.component.inc
  templates/pager/pager.tpl.php
  templates/site_header/site_header.component.inc
  templates/site_switcher/site_switcher.component.inc
  templates/social_icon/social_icon.component.inc
  templates/splash/splash.component.inc
  templates/status_messages/status_messages.component.inc
  templates/tags/tags.component.inc
  templates/textfield/textfield--form--views-exposed-form.tpl.php
  templates/views_more/views-more.tpl.php
  templates/views_view_grid/views_view_grid.component.inc
  tests/features/bootstrap/FeatureContext.php
  theme-settings.php
Labels: 0.x, Ready to review

#87 Issue #81: Update gitignore file.
  .gitignore
Labels: 0.x, Ready to review

#83 Issue #78: Add missing description in form element checkbox.
  templates/form_element/form-element--checkbox.tpl.php
Labels: 0.x, Ready to review

#85 Issue #84: Fix status messages component.
  templates/status_messages/status-messages.tpl.php
  templates/status_messages/status_messages.component.inc
Labels: 0.x, Ready to review

#93 Issue #92: Update composer configuration.
  composer.json
Labels: 0.x, Ready to review

#89 Issue #88: Fix form_element component.
  templates/form_element/form-element--checkbox.tpl.php
  templates/form_element/form-element--radio.tpl.php
  templates/form_element/form-element.tpl.php
Labels: 0.x, Ready to review

#91 Issue #90: Enable Behat tests.
  composer.json
  grumphp.yml.dist
  templates/ds/ds-2col-stacked-fluid.tpl.php
  templates/pager/pager.tpl.php
Labels: 0.x, Ready to review

#95 Issue #94: Fix type hints and functions signature.
  includes/alter/css.inc
  includes/alter/form.inc
  includes/alter/html_head.inc
  includes/alter/js.inc
  templates/easy_breadcrumb/easy_breadcrumb.component.inc
  templates/footer/footer.component.inc
  templates/grid/grid.component.inc
  templates/labels/labels.component.inc
  templates/lang_select_site/lang_select_site.component.inc
  templates/link/link.component.inc
  templates/link_blocks/link_blocks.component.inc
  templates/logo/logo.component.inc
  templates/meta/meta.component.inc
  templates/page_header/page_header.component.inc
  templates/search_bar/search_bar.component.inc
  templates/site_header/site_header.component.inc
  templates/site_slogan/site_slogan.component.inc
  templates/site_switcher/site_switcher.component.inc
  templates/splash/splash.component.inc
  templates/status_messages/status_messages.component.inc
  templates/tags/tags.component.inc
  templates/views_mini_pager/views_mini_pager.component.inc
Labels: 0.x, Ready to review

#66 NEPT-1926: Use attributes variables from the component as well.
  templates/search_bar/search_bar.component.inc
Labels: 0.x, Ready to review

#61 NEPT-1419: Site slogan component no longer shows
  templates/site_header/site-header.tpl.php
  templates/site_header/site_header.component.inc
  templates/site_slogan/site_slogan.component.inc
Labels: 0.x, Ready to review, bug

#100 Issue #99: Update composer.json.
  composer.json
Labels: 0.x, Ready to review

#101 Issue #98: Update ECL version to 0.24.
  assets/scripts/europa.js
  assets/styles/europa.css
  assets/styles/europa.css.map
Labels: enhancement

#104 Issue #103: Remove the pager definition hook as it has been included in Atomium
  templates/pager/pager.component.inc
Labels: Ready to review

#107 Update docker and runner configuration
  docker-compose.yml
  runner.yml.dist
  tests/composer.json
Labels: Ready to review

#112 Issue #111: Remove table definition hook as it has been moved to Atomium
  .drone.yml
  composer.json
  templates/meta/meta.component.inc
  templates/page_header/page_header.component.inc
  templates/table/table.component.inc
Labels: Ready to review, enhancement
