Repository ec-europa/ec_europa, pull requests merged in 2019-06, with the labels that each got.

#154 Issue #153: Fix components.
  templates/item_list/item-list--status-messages.tpl.php
  templates/status_messages/status_messages.component.inc
Labels: Ready to review, bug

#158 Update atomium v. 2.28 and update pager accordingly.
  composer.json
  templates/ds/ds-2col-stacked-fluid.tpl.php
  templates/link/link.component.inc
  templates/pager/pager.component.inc
  templates/pager_current/pager-current.tpl.php
  templates/pager_next/pager_next.component.inc
  templates/pager_previous/pager_previous.component.inc
Labels: 0.x, enhancement

#161 Update drupal convention version 1.4.15.
  composer.json
  templates/ds/ds-2col-stacked-fluid.tpl.php
Labels: 0.x, enhancement

#160 159 update drupal convention 0.0.x
  composer.json
  template.php
  templates/checkboxes/checkboxes.component.inc
  templates/pager/pager.component.inc
  templates/password/password.component.inc
  templates/radios/radios.component.inc
  templates/select/select.component.inc
  templates/textfield/textfield.component.inc
  templates/views_view_grid/views_view_grid.component.inc
Labels: 0.0.x, enhancement
