Repository ec-europa/ec_europa, pull requests merged in 2019-05, with the labels that each got.

#138 Issue #137: Use Taskman
  .drone.yml
  README.md
  composer.json
  taskman.yml.dist
  templates/comment/comment.tpl.php
  templates/ds/ds-1col-wrapper.tpl.php
  templates/ds/ds-1col.tpl.php
  templates/ds/ds-2col-stacked-fluid.tpl.php
  templates/ds/ds-2col.tpl.php
  templates/ds/ds-3col-equal-width.tpl.php
  templates/ds/ds-3col-stacked-equal-width.tpl.php
  templates/ds/ds-3col-stacked-fluid.tpl.php
  templates/ds/ds-3col-stacked.tpl.php
  templates/ds/ds-3col.tpl.php
  templates/ds/ds-4col.tpl.php
  templates/html/html.tpl.php
  templates/maintenance_page/maintenance-page--offline.tpl.php
  templates/maintenance_page/maintenance-page.tpl.php
  templates/pager/pager.component.inc
  templates/views_view_table/views-view-table.tpl.php
Labels: enhancement

#140 Issue #139: Ensure link title is rendered in plain text.
  taskman.yml.dist
  templates/easy_breadcrumb/easy_breadcrumb.component.inc
  templates/html/html.tpl.php
Labels: bug

#147 Issue #146: Remove deprecated method
  composer.json
  templates/form_element_label/form_element_label.component.inc
Labels: bug

#151 Issue #150: Revert "NEPT-1315: Adapt ec_europa theme to the new version of easy-breadcrumb module.
  composer.json
  templates/easy_breadcrumb/easy_breadcrumb.component.inc
Labels: Ready to review, bug
